name: build-and-push-docker

on:
  push:
    branches: [ main ]        # publish image on pushes to main
  pull_request:
    branches: [ main ]        # PRs build only (no push)
  workflow_dispatch:          # manual "Run workflow" button

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write         # required to push to ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (PRs) / Build+Push (main)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/jtn34/user_management:latest
            ghcr.io/jtn34/user_management:${{ github.sha }}

